var acsObject = {
	Events: {
		fields: [{
			key: 'acls',
			type: 'object'
		}, {
			key: 'custom_fields',
			type: 'string'
		}, {
			key: 'created_at',
			type: 'date'
		}, {
			key: 'id',
			type: 'string'
		}, {
			key: 'details',
			type: 'string'
		}, {
			key: 'duration',
			type: 'numver'
		}, {
			key: 'ical',
			type: 'string'
		}, {
			key: 'name',
			type: 'string'
		}, {
			key: 'place',
			type: 'object'
		}, {
			key: 'photo',
			type: 'object'
		}, {
			key: 'recurring',
			type: 'string'
		}, {
			key: 'updated_at',
			type: 'object'
		}, {
			key: 'user',
			type: 'object'
		}, {
			key: 'recurring_count',
			type: 'numver'
		}, {
			key: 'recurring_until',
			types: ['date', 'string']
		}, {
			key: 'start_time',
			types: ['date', 'string']
		}],
		methods: {
			batchDelete: {
				httpMethod: 'DELETE',
				restMethod: 'batch_delete',
				requiredParam: [],
				optionalParam: [{
					key: 'where',
					type: 'string'
				}]
			},
			count: {
				httpMethod: 'GET',
				requiredParam: [],
				optionalParam: []
			},
			create: {
				httpMethod: 'POST',
				requiredParam: [{
					key: 'name',
					type: 'string'
				}, {
					key: 'start_time',
					types: ['date', 'string']
				}],
				optionalParam: [{
					key: 'details',
					type: 'string'
				}, {
					key: 'duration',
					type: 'number'
				}, {
					key: 'recurring',
					type: 'string'
				}, {
					key: 'recurring_count',
					type: 'number'
				}, {
					key: 'recurring_until',
					type: 'date'
				}, {
					key: 'place_id',
					type: 'string'
				}, {
					key: 'photo',
					type: 'object'
				}, {
					key: 'photo_id',
					type: 'string'
				}, {
					key: 'custom_fields',
					type: 'string'
				}, {
					key: 'acl_name',
					type: 'string'
				}, {
					key: 'acs_id',
					type: 'string'
				}, {
					key: 'tags',
					type: 'string'
				}, {
					key: 'user_id',
					type: 'string'
				}, {
					key: 'pretty_json',
					type: 'boolean'
				}]
			},
			delete: {
				httpMethod: 'DELETE',
				requiredParam: [{
					key: 'event_id',
					type: 'string'
				}],
				optionalParam: [{
					key: 'user_id',
					type: 'string'
				}, {
					key: 'pretty_json',
					type: 'boolean'
				}]
			},
			query: {
				httpMethod: 'GET',
				requiredParam: [],
				optionalParam: [{
					key: 'page',
					type: 'number'
				}, {
					key: 'per_page',
					type: 'number'
				}, {
					key: 'limit',
					type: 'number'
				}, {
					key: 'skip',
					type: 'number'
				}, {
					key: 'where',
					type: 'string'
				}, {
					key: 'order',
					type: 'string'
				}, {
					key: 'sel',
					type: 'string'
				}, {
					key: 'show_user_like',
					type: 'boolean'
				}, {
					key: 'unsel',
					type: 'string'
				}, {
					key: 'response_json_depth',
					type: 'number'
				}, {
					key: 'pretty_json',
					type: 'boolean'
				}]
			},
			queryOccurrences: {
				httpMethod: 'GET',
				restMethod: 'query/occurrences',
				requiredParam: [],
				optionalParam: [{
					key: 'page',
					type: 'number'
				}, {
					key: 'per_page',
					type: 'number'
				}, {
					key: 'limit',
					type: 'number'
				}, {
					key: 'skip',
					type: 'number'
				}, {
					key: 'where',
					type: 'string'
				}, {
					key: 'order',
					type: 'string'
				}, {
					key: 'sel',
					type: 'string'
				}, {
					key: 'unsel',
					type: 'string'
				}, {
					key: 'response_json_depth',
					type: 'number'
				}, {
					key: 'pretty_json',
					type: 'boolean'
				}]
			},
			search: {
				httpMethod: 'GET',
				requiredParam: [],
				optionalParam: [{
					key: 'page',
					type: 'number'
				}, {
					key: 'per_page',
					type: 'number'
				}, {
					key: 'place_id',
					type: 'string'
				}, {
					key: 'user_id',
					type: 'string'
				}, {
					key: 'latitude',
					type: 'number'
				}, {
					key: 'longitude',
					type: 'number'
				}, {
					key: 'distance',
					type: 'number'
				}, {
					key: 'start_time',
					type: 'date'
				}, {
					key: 'q',
					type: 'string'
				}, {
					key: 'response_json_depth',
					type: 'number'
				}, {
					key: 'pretty_json',
					type: 'boolean'
				}]
			},
			searchOccurrences: {
				httpMethod: 'GET',
				restMethod: 'search/occurrences',
				requiredParam: [],
				optionalParam: [{
					key: 'page',
					type: 'number'
				}, {
					key: 'per_page',
					type: 'number'
				}, {
					key: 'place_id',
					type: 'string'
				}, {
					key: 'user_id',
					type: 'string'
				}, {
					key: 'latitude',
					type: 'number'
				}, {
					key: 'longitude',
					type: 'number'
				}, {
					key: 'distance',
					type: 'number'
				}, {
					key: 'start_time',
					type: 'date'
				}, {
					key: 'end_time',
					type: 'date'
				}, {
					key: 'q',
					type: 'string'
				}, {
					key: 'response_json_depth',
					type: 'number'
				}, {
					key: 'pretty_json',
					type: 'boolean'
				}]
			},
			show: {
				httpMethod: 'GET',
				requiredParam: [],
				optionalParam: [{
					key: 'event_id',
					type: 'string'
				}, {
					key: 'events_id',
					type: 'string'
				}, {
					key: 'response_json_depth',
					type: 'number'
				}, {
					key: 'show_user_like',
					type: 'boolean'
				}, {
					key: 'pretty_json',
					type: 'boolean'
				}]
			},
			showOccurrences: {
				httpMethod: 'GET',
				restMethod: 'show/occurrences',
				requiredParam: [],
				optionalParam: [{
					key: 'event_id',
					type: 'string'
				}, {
					key: 'page',
					type: 'number'
				}, {
					key: 'per_page',
					type: 'number'
				}, {
					key: 'response_json_depth',
					type: 'number'
				}, {
					key: 'pretty_json',
					type: 'boolean'
				}]
			},
			update: {
				httpMethod: 'PUT',
				requiredParam: [{
					key: 'event_id',
					type: 'string'
				}],
				optionalParam: [{
					key: 'name',
					type: 'string'
				}, {
					key: 'start_time',
					types: ['date', 'string']
				}, {
					key: 'duration',
					type: 'number'
				}, {
					key: 'recurring',
					type: 'string'
				}, {
					key: 'recurring_count',
					type: 'number'
				}, {
					key: 'recurring_until',
					type: 'date'
				}, {
					key: 'details',
					type: 'string'
				}, {
					key: 'place_id',
					type: 'string'
				}, {
					key: 'photo',
					type: 'object'
				}, {
					key: 'photo_id',
					type: 'string'
				}, {
					key: 'tags',
					type: 'string'
				}, {
					key: 'custom_fields',
					type: 'string'
				}, {
					key: 'acl_name',
					type: 'string'
				}, {
					key: 'acl_id',
					type: 'string'
				}, {
					key: 'user_id',
					type: 'string'
				}, {
					key: 'pretty_json',
					type: 'boolean'
				}]
			}
		}
	}
};

module.exports = acsObject;
