var acsObject = {
	Reviews: {
		fields: [{
			key: 'checkin',
			type: 'object'
		}, {
			key: 'content',
			type: 'string'
		}, {
			key: 'created_at',
			type: 'date'
		}, {
			key: 'custom_fields',
			types: ['string', 'object']
		}, {
			key: 'event',
			type: 'object'
		}, {
			key: 'photo',
			type: 'object'
		}, {
			key: 'place',
			type: 'object'
		}, {
			key: 'post',
			type: 'object'
		}, {
			key: 'rating',
			type: 'string'
		}, {
			key: 'ratings_average',
			type: 'number'
		}, {
			key: 'ratings_count',
			type: 'number'
		}, {
			key: 'ratings_summary',
			type: 'object'
		}, {
			key: 'review',
			type: 'object'
		}, {
			key: 'reviews',
			type: 'array'
		}, {
			key: 'reviews_count',
			type: 'number'
		}, {
			key: 'status',
			type: 'object'
		}, {
			key: 'tags',
			type: 'array'
		}, {
			key: 'updated_at',
			type: 'date'
		}, {
			key: 'user',
			type: 'object'
		}],
		methods: {
			batchDelete: {
				httpMethod: 'DELETE',
				restMethod: 'batch_delete',
				requiredParam: [],
				optionalParam: [{
					key: 'where',
					type: 'object'
				}]
			},
			count: {
				httpMethod: 'GET',
				requiredParam: [],
				optionalParam: []
			},
			create: {
				httpMethod: 'POST',
				requiredParam: [],
				optionalParam: [{
					key: 'post_id',
					type: 'string'
				}, {
					key: 'photo_id',
					type: 'string'
				}, {
					key: 'user_object_id',
					type: 'string'
				}, {
					key: 'event_id',
					type: 'string'
				}, {
					key: 'place_id',
					type: 'string'
				}, {
					key: 'checkin_id',
					type: 'string'
				}, {
					key: 'review_id',
					type: 'string'
				}, {
					key: 'custom_object_id',
					type: 'string'
				}, {
					key: 'status_id',
					type: 'string'
				}, {
					key: 'content',
					type: 'string'
				}, {
					key: 'rating',
					type: 'string'
				}, {
					key: 'allow_duplicate',
					type: 'boolean'
				}, {
					key: 'tags',
					type: 'string'
				}, {
					key: 'custom_fields',
					types: ['string', 'object']
				}, {
					key: 'acl_name',
					type: 'string'
				}, {
					key: 'acl_id',
					type: 'string'
				}, {
					key: 'user_id',
					type: 'string'
				}]
			},
			delete: {
				httpMethod: 'DELETE',
				requiredParam: [{
					key: 'review_id',
					type: 'string'
				}],
				optionalParam: [{
					key: 'post_id',
					type: 'string'
				}, {
					key: 'photo_id',
					type: 'string'
				}, {
					key: 'place_id',
					type: 'string'
				}, {
					key: 'user_id',
					type: 'string'
				}, {
					key: 'event_id',
					type: 'string'
				}, {
					key: 'checkin_id',
					type: 'string'
				}, {
					key: 'review_object_id',
					type: 'string'
				}, {
					key: 'custom_object_id',
					type: 'string'
				}, {
					key: 'status_id',
					type: 'string'
				}]
			},
			remove: {
				httpMethod: 'DELETE',
				restMethod: 'delete',
				requiredParam: [{
					key: 'review_id',
					type: 'string'
				}],
				optionalParam: [{
					key: 'post_id',
					type: 'string'
				}, {
					key: 'photo_id',
					type: 'string'
				}, {
					key: 'place_id',
					type: 'string'
				}, {
					key: 'user_id',
					type: 'string'
				}, {
					key: 'event_id',
					type: 'string'
				}, {
					key: 'checkin_id',
					type: 'string'
				}, {
					key: 'review_object_id',
					type: 'string'
				}, {
					key: 'custom_object_id',
					type: 'string'
				}, {
					key: 'status_id',
					type: 'string'
				}]
			},
			query: {
				httpMethod: 'GET',
				requiredParam: [],
				optionalParam: [{
					key: 'post_id',
					type: 'string'
				}, {
					key: 'photo_id',
					type: 'string'
				}, {
					key: 'user_id',
					type: 'string'
				}, {
					key: 'event_id',
					type: 'string'
				}, {
					key: 'place_id',
					type: 'string'
				}, {
					key: 'checkin_id',
					type: 'string'
				}, {
					key: 'review_id',
					type: 'string'
				}, {
					key: 'custom_object_id',
					type: 'string'
				}, {
					key: 'status_id',
					type: 'string'
				}, {
					key: 'owner_id',
					type: 'string'
				}, {
					key: 'page',
					type: 'number'
				}, {
					key: 'per_page',
					type: 'number'
				}, {
					key: 'limit',
					type: 'number'
				}, {
					key: 'skip',
					type: 'number'
				}, {
					key: 'where',
					type: 'object'
				}, {
					key: 'order',
					type: 'string'
				}, {
					key: 'sel',
					type: 'object'
				}, {
					key: 'show_user_like',
					type: 'boolean'
				}, {
					key: 'unsel',
					type: 'object'
				}, {
					key: 'response_json_depth',
					type: 'number'
				}]
			},
			show: {
				httpMethod: 'GET',
				requiredParam: [{
					key: 'review_id',
					type: 'string'
				}],
				optionalParam: [{
					key: 'post_id',
					type: 'string'
				}, {
					key: 'photo_id',
					type: 'string'
				}, {
					key: 'user_id',
					type: 'string'
				}, {
					key: 'event_id',
					type: 'string'
				}, {
					key: 'place_id',
					type: 'string'
				}, {
					key: 'checkin_id',
					type: 'string'
				}, {
					key: 'custom_object_id',
					type: 'string'
				}, {
					key: 'status_id',
					type: 'string'
				}, {
					key: 'show_user_like',
					type: 'boolean'
				}, {
					key: 'review_object_id',
					type: 'string'
				}, {
					key: 'response_json_depth',
					type: 'number'
				}]
			},
			update: {
				httpMethod: 'PUT',
				requiredParam: [{
					key: 'review_id',
					type: 'string'
				}],
				optionalParam: [{
					key: 'post_id',
					type: 'string'
				}, {
					key: 'photo_id',
					type: 'string'
				}, {
					key: 'user_object_id',
					type: 'string'
				}, {
					key: 'event_id',
					type: 'string'
				}, {
					key: 'place_id',
					type: 'string'
				}, {
					key: 'checkin_id',
					type: 'string'
				}, {
					key: 'review_object_id',
					type: 'string'
				}, {
					key: 'custom_object_id',
					type: 'string'
				}, {
					key: 'status_id',
					type: 'string'
				}, {
					key: 'content',
					type: 'string'
				}, {
					key: 'rating',
					type: 'string'
				}, {
					key: 'user_id',
					type: 'string'
				}, {
					key: 'allow_duplicate',
					type: 'boolean'
				}, {
					key: 'tags',
					type: 'string'
				}, {
					key: 'custom_fields',
					types: ['string', 'object']
				}, {
					key: 'acl_name',
					type: 'string'
				}, {
					key: 'acl_id',
					type: 'string'
				}]
			}
		}
	}
};

module.exports = acsObject;
